### ISSUE TITLE
Add an option to disable `Alt + Number`

### ISSUE THREAD

**Issue by Kienyew** [SqYtCO/shortcuts#1]
Went through a lot of searches, I can't find any available option to disable `Alt + Number` to switch tab in firefox. Is there any possibility achieve that.

**Comment by taminob** [comment]
Sorry for the late reply, looks like I messed up my GitHub notification settings. In case, this issue is still up-to-date:
I was not able to prevent the usage of this shortcut entirely using the extension. Using the following code (for ALT+1) it's possible to disable to shortcut for the site context, but this will not prevent the shortcut when the focus is on e.g. the url bar. Also, this has to be done on every document switch and might conflict with some websites.
```
document.onkeydown = function(e){
  if(e.altKey && e.keyCode == '1'.charCodeAt(0)){
    e.preventDefault();
  }
}
```
This can be used as a command in manifest.json to prevent the shortcut ALT+1 when the focus is not on any website:
```
"dont_use_alt_1": {
    "suggested_key": { "default": "Alt+1" }
}
```
To disable the shortcuts completely, I recommend to rely on your WM/DE. If you set the shortcut to some kind of empty action, Firefox should not be able to overwrite this. Tested for i3/sway.

However, since I do not see any benefit in this feature except that the shortcut can be used for something else which would conflict with all possible solutions I can think of, I will close the issue.
